# Generated by Django 5.2.1 on 2025-05-25 12:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Word',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=64, unique=True, verbose_name='слово_глобально')),
                ('idf', models.FloatField(default=0.0)),
            ],
        ),
        migrations.CreateModel(
            name='WordsInDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid_document_name', models.CharField(max_length=64, verbose_name='имя документа')),
                ('tf', models.FloatField(verbose_name='idf')),
                ('word', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tfidfapp.word')),
            ],
        ),
    ]
